[project]
name = "a-star"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ruff>=0.14.2",
]

[tool.ruff]
line-length = 88